listen: 0.0.0.0:443
redirecthttps: 0.0.0.0:80

vhosts:
  ##V2RAY@- name: FAKEV2DOMAIN
    ##V2RAY@tlsoffloading: true
    ##V2RAY@managedcert: true
    ##V2RAY@keytype: p256
    ##V2RAY@alpn: h2,http/1.1
    ##V2RAY@protocols: tls12,tls13
    ##V2RAY@http:
      ##CDN@paths:
        ##CDN@- path: /FAKECDNPATH
        ##CDN@  handler: proxyPass
        ##CDN@  args: 127.0.0.1:3566
      ##V2RAY@handler: fileServer
      ##V2RAY@args: /var/www/html
    ##V2RAY@default:
      ##V2RAY@handler: proxyPass
      ##V2RAY@args: unix:/tmp/v2ray-ds/v2ray.sock

  ##SUBAPI@- name: FAKEAPIDOMAIN
    ##SUBAPI@tlsoffloading: true
    ##SUBAPI@managedcert: true
    ##SUBAPI@keytype: p256
    ##SUBAPI@alpn: http/1.1
    ##SUBAPI@protocols: tls12,tls13
    ##SUBAPI@http:
      ##SUBAPI@handler: proxyPass
      ##SUBAPI@args: 127.0.0.1:25500

  ##MTPROTO@- name: FAKEMTDOMAIN
    ##MTPROTO@tlsoffloading: false
    ##MTPROTO@default:
      ##MTPROTO@handler: proxyPass
      ##MTPROTO@args: 127.0.0.1:3128

  ##TROJAN@- name: FAKETJDOMAIN
    ##TROJAN@tlsoffloading: true
    ##TROJAN@managedcert: true
    ##TROJAN@keytype: p256
    ##TROJAN@alpn: h2,http/1.1
    ##TROJAN@protocols: tls12,tls13
    ##TROJAN@http:
      ##TROJAN@handler: fileServer
      ##TROJAN@args: /var/www/html
    ##TROJAN@default:
      ##TROJAN@handler: proxyPass
      ##TROJAN@args: 127.0.0.1:3567